//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VISHWASAMUDRA.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class LoginUser
    {
        public int Userid { get; set; }
        [Required(ErrorMessage ="pls enter UserName")]
        public string Username { get; set; }
        [Required(ErrorMessage ="pls enter UserPassword")]
        public string Userpwd { get; set; }
        public bool Status { get; set; }
    }
}
